version: "3.8"
services:
  react-app:
    build: ./client
    container_name: client
    ports:
      - "3000:3000"
    networks:
      pern-app:
    stdin_open: true
    tty: true

  api-server:
    build: ./
    container_name: server
    ports:
      - "5000:5000"
    depends_on:
      - postgres_db  
    networks:
      pern-app:

  postgres:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DATABASE: ${PG_DATABASE}
    ports:
      - "5438:5432"
    networks:
      pern-app:
    volumes: 
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./pgdata:/var/lib/postgresql/data

networks:
  pern-app:
volumes:
  pgdata:
    driver: local
