version: "3.8"
services:
  react-app:
    build: ./client
    container_name: client
    ports:
      - "3000:3000"
    networks:
      pern-app:
    stdin_open: true
    tty: true

  api-server:
    build: ./
    container_name: server
    ports:
      - "5000:5000"
    links:
      - postgres
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    networks:
      pern-app:

  postgres:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    ports:
      - "5432:5432"
    networks:
      pern-app:
    volumes:
      - ./pgdata:/var/lib/postgresql/data

networks:
  pern-app:
volumes:
  pgdata:
    driver: local
